/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The public keys access tokens are signed with.
         * @description Public and unauthenticated by definition: it carries only public keys, and a
         *     verifier needs it before it holds any credential to authenticate with.
         */
        get: operations["jwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — answers as long as the process is serving requests. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe — additionally verifies the database is reachable, so an
         *     orchestrator does not route traffic to an instance that cannot serve it.
         */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/athlete/maxes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everything the athlete has entered. */
        get: operations["show_maxes"];
        /**
         * Replaces the athlete's maxes with exactly what is sent.
         * @description A `PUT` of the whole document, not a patch: what the client holds is one
         *     form, and a partial upsert would leave "clear the max I entered by mistake"
         *     with no representation at all. A key absent from the body is therefore a key
         *     deleted, and the whole thing is one transaction so a half-applied form is not
         *     a state the athlete can end up in.
         *
         *     Removing a max cannot break a program already running. A prescriptive block
         *     snapshots the maxes it was started from (D-03) and an adaptive one keeps its
         *     training max in `State`, so neither reads this table again after enrolment —
         *     which is also why editing a number here does not retroactively rewrite
         *     sessions the athlete has already been shown (D-07).
         */
        put: operations["replace_maxes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchanges an athlete's email and password for a token pair. */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ends the session the refresh token belongs to, and revokes the access token
         *     presented alongside it.
         * @description Both credentials are revoked because revoking only the refresh token leaves
         *     the caller holding a bearer token that keeps working for up to its full
         *     lifetime after they pressed "sign out". The access token's `jti` goes on the
         *     denylist (`auth::denylist`), which the authenticated extractor already
         *     consults as part of the query it was making anyway.
         *
         *     Both are optional, and the sensible behaviours differ:
         *
         *     * refresh token only — the ordinary BFF logout. The session dies; any access
         *       token already handed out lives until its `exp`, because nothing links an
         *       access token to a refresh family and inventing that link would mean
         *       storing every access token, which is precisely what ADR-0003 avoids. The
         *       15-minute ceiling is the residual exposure, and it is why the access token
         *       should be sent too.
         *     * access token only — a client that never held a refresh token, or lost it.
         *       The token presented is revoked immediately.
         *
         *     Idempotent, and it still never reveals whether either credential existed: an
         *     attacker holding a stolen token must not learn anything by logging it out.
         *     A request carrying neither credential is a malformed request, not a silent
         *     success, and is the one case that is refused.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The athlete the presented access token identifies. Also the smallest
         *     possible proof that the extractor works.
         */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchanges a refresh token for a new pair, invalidating the one presented.
         * @description Presenting a token that was already exchanged revokes every token in its
         *     family — see `auth::refresh` for why.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Creates an athlete and signs them straight in.
         * @description Registration is open (D-02). The inherited design was invitation-only, with a
         *     `bootstrap` binary that refused to run twice; that is the wrong shape for a
         *     product whose unit is one athlete.
         *
         *     Three things about this handler are deliberate.
         *
         *     **It answers 409 when the address is taken**, which is an account
         *     enumeration oracle, and there is no way to build an open registration
         *     endpoint without one: the alternative — accept everything and say "check your
         *     email" — requires mail, and v1 has no SMTP by decision (D-02, D-14). Saying
         *     so plainly is better than a refusal the athlete cannot act on. The detail
         *     text is neutral about *why*, so it reads the same to whoever receives it.
         *
         *     **The password is checked before it is hashed and before the row exists.**
         *     The policy needs the address and the name as context — they are the first two
         *     things anyone guessing this account tries — so validation has to run in this
         *     order rather than in the order the fields arrive.
         *
         *     **It is not throttled.** `auth::throttle` exists to bound guessing against an
         *     address that already has an account (SP 800-63B-4 §3.2.2), and there is
         *     nothing here to guess. What does bound this endpoint is the Argon2 hash it
         *     spends before touching the database, including on a duplicate address.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every program this athlete has run, current one first.
         * @description This is how a client that has been reloaded finds its way back: the enrolment
         *     id it needs for `next-session` and for `POST /v1/workouts` is not something it
         *     can derive, and a BFF cookie holding it would be a second source of truth for
         *     a fact the database already knows.
         *
         *     Both a `status` filter and an active-first ordering, which is not
         *     belt-and-braces. The filter is what a client asking "what am I running"
         *     should send. The ordering is what keeps the *unfiltered* call — "programs
         *     I've run", the D-13 reading — from making the client sort to find the live
         *     one. A default order that answers the common question is worth more than one
         *     that is merely chronological, and it costs a boolean in the `order by`.
         */
        get: operations["list_enrollments"];
        put?: never;
        /**
         * Starts a program for the authenticated athlete.
         * @description The engine validates: `start()` derives the whole block (or, for an adaptive
         *     program, every training max) purely so that a missing max fails here, at
         *     enrolment, rather than as a zero-kilo prescription on day one of week one.
         *     That refusal reaches the caller as a 422 naming the exercise key — see the
         *     `ProgramError` conversion in `crate::error`.
         *
         *     Nothing stops an athlete holding several enrolments at once, including in the
         *     same program. The schema's active-enrolment index is deliberately not unique:
         *     running a squat block and a bench block side by side is a product question
         *     nobody has answered yet, and a constraint would answer it by accident.
         */
        post: operations["create_enrollment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/enrollments/{id}/next-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the athlete is doing next. **Read-only** (D-08).
         * @description No row is written, no timer starts, and no state moves. `started_at` is
         *     stamped on commit, which happens on the phone and arrives later as a
         *     `POST /v1/workouts` — this endpoint exists precisely so that looking is free.
         *     If this handler ever acquires a write, the distinction D-08 is built on has
         *     been lost. It acquired a second *read* in phase 5, for the pace projection,
         *     and that is the line: reads are what "free" means.
         */
        get: operations["next_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every exercise a max may be entered for.
         * @description Authenticated for the same reason the program catalogue is: nothing here is
         *     anybody's data, but opening an endpoint later is additive and closing one is
         *     not (D-12).
         */
        get: operations["list_exercises"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every program an athlete can enrol in. */
        get: operations["list_programs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/programs/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One program's catalogue entry.
         * @description Deliberately the same shape the list returns rather than a richer one. A
         *     detail view that showed the actual prescribed sessions would have to derive
         *     them from the athlete's maxes, which is what enrolling is for — and showing a
         *     preview built from maxes the athlete has not entered would mean inventing
         *     numbers.
         */
        get: operations["show_program"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Where a year of training went.
         * @description # One round trip, and nothing stored
         *
         *     Four queries, no writes, and no table behind any of it (D-13, amended). The
         *     estimate is [`athletos_training::estimate`] over stored sets, load and drift
         *     are sums over the same rows, the training max is `readout()` applied to the
         *     `state_before` [`crate::advances`] already records, and the intervals come
         *     off [`crate::timing`]'s own walk. Every figure here is implied by rows that
         *     exist for other reasons, which is exactly why a metrics table was declined:
         *     a stored total is a second copy of an arithmetic fact, and the day it
         *     disagrees with the rows there is no way to tell which one is wrong.
         *
         *     # The scope, and the index that does not serve it
         *
         *     `workouts` has no `athlete_id`, so ownership arrives through the join on
         *     `enrollments` in all four queries — the same shape, and the same accepted
         *     cost, that [`crate::routes::workouts::history`] documents at length. The
         *     window bounds it: this is one person's twelve months, which is hundreds of
         *     sessions and low thousands of sets at the volume this product is designed
         *     for.
         *
         *     # A deviation from the spec: fixed, not overridable
         *
         *     The spec calls the window "twelve months by default, overridable". This
         *     ships the default and not the override — no query parameter — because
         *     building one was out of scope for this pass. What it does carry is
         *     [`ProgressView::window_months`], so a client rendering `overall.sessions`
         *     can caption it correctly without knowing [`WINDOW_MONTHS`] exists. That
         *     closes the half of the gap that would otherwise force a client to hardcode
         *     a server-side constant (D-11); it does not close the other half, and an
         *     athlete cannot yet ask this endpoint for eighteen months instead of twelve.
         */
        get: operations["athlete_progress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Everything the athlete has logged, newest first.
         * @description # Pagination, and the index that does not exist
         *
         *     Offset and limit, not a keyset cursor. Keyset is the stabler construction and
         *     it is not the one that fits here: the sort key would have to be
         *     `(started_at, id)` to break ties, and the only index over `workouts` is
         *     `(enrollment_id, started_at desc)`, which carries neither `athlete_id` nor
         *     `id`. So keyset would buy no index advantage and would trade one form of
         *     drift for an opaque cursor. The drift offset does have is real and small: a
         *     workout submitted while the athlete is paging shifts rows by one, which in a
         *     "load more" list read by one person is a repeated or skipped row, not a wrong
         *     answer.
         *
         *     The honest cost of the unfiltered call is that Postgres materialises and
         *     sorts one athlete's *entire* workout history per page. `workouts` has no
         *     `athlete_id`, so the scope comes through a join and no index over `workouts`
         *     can answer the ordering — this is a sort, and it is bounded by how many
         *     sessions one person has logged. At the hundreds this is designed for that
         *     costs nothing worth measuring. If it ever does, the fix is to denormalise
         *     `athlete_id` onto `workouts` with an index on `(athlete_id, started_at
         *     desc)`; that is an additive migration, and adding the column now — untested,
         *     unmeasured, and duplicating a fact `enrollments` already owns — is exactly
         *     the speculative move the schema's own comments argue against.
         *
         *     Supplying `enrollment_id` sidesteps all of it: that query is one walk of the
         *     existing index, in order, and stops at the limit.
         */
        get: operations["list_workouts"];
        put?: never;
        /** Records a finished session and advances the program exactly once. */
        post: operations["submit_workout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workouts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One workout and every set of it.
         * @description A separate endpoint rather than an `?include=sets` flag on the list, for the
         *     interaction it serves: expand-on-tap opens one row at a time, and an include
         *     flag would fetch the sets for a whole page whether or not anything was
         *     expanded — around a thousand rows to render twenty-five dates, on a phone.
         *     A submitted workout is also immutable, so this response can be cached hard by
         *     the client where a list response cannot. And the choice is not final in the
         *     direction that matters: an `include` flag can be added later if the extra
         *     round trip ever hurts, whereas a field cannot be taken back out of the list
         *     (D-12).
         */
        get: operations["show_workout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The whole screen, in one round trip.
         *
         *     # Why the component is called `AthleteProgress`
         *
         *     `routes::enrollments::ProgressView` — sessions completed out of a block —
         *     has been shipping under the component name `ProgressView` since the first
         *     release, and utoipa names a component after the type's last path segment.
         *     Registering a second `ProgressView` does not collide loudly; it overwrites,
         *     and the generated TypeScript would silently start describing this screen
         *     wherever an enrolment's `progress` field is read. D-12 forbids changing what
         *     an existing `/v1` field means, so the older name stays with the older type
         *     and the newcomer takes an alias. The Rust name is unchanged and the JSON on
         *     the wire is unaffected: this renames a schema, not a field.
         */
        AthleteProgress: {
            lifts: components["schemas"]["LiftTrend"][];
            overall: components["schemas"]["Indicator"][];
            programs: components["schemas"]["ProgramTotals"][];
            sessions: components["schemas"]["SessionFigures"][];
            /**
             * Format: int32
             * @description How many months of history `lifts`, `sessions` and `overall` cover —
             *     [`WINDOW_MONTHS`], carried onto the wire. `bests` is the one exception
             *     and is not bounded by it (see that function). Named rather than left
             *     implicit so a client can caption `overall`'s `sessions` figure as
             *     "Sessions (last N months)" without hardcoding a number only the server
             *     knows — the same reason `indicators_from`'s doc comment gives for why
             *     the client is never told what a metric means beyond its `unit` (D-11).
             * @example 12
             */
            window_months: number;
        };
        /**
         * @description A verified athlete.
         *
         *     Deliberately just the id: v1 has one athlete per account and no teams
         *     (D-14), so there is nothing else an authorization decision needs. Coaching
         *     arrives in v2 as a coach↔athlete relation, which is a different shape from
         *     the generic team roles this replaced — so there is nothing here to keep
         *     warm for it either.
         */
        AuthenticatedAthlete: {
            /** Format: uuid */
            athlete_id: string;
        };
        /**
         * @description One cell of the rep-max grid: the heaviest weight lifted for **at least**
         *     `reps` reps, and the set it came from.
         */
        Best: {
            /**
             * Format: int32
             * @description What was actually done at that weight — always at least `reps`.
             */
            actual_reps: number;
            /** Format: date-time */
            at: string;
            /**
             * Format: int32
             * @description The bucket, not the reps performed.
             */
            reps: number;
            /** Format: double */
            weight: number;
            /** Format: uuid */
            workout_id: string;
        };
        /** @description One exercise and everything prescribed for it in this session. */
        BlockView: {
            /**
             * @description How to do it, from the compiled exercise registry.
             *
             *     Resolved here rather than stored with the session, so a corrected cue
             *     reaches every session including ones already logged. The engine's `Block`
             *     deliberately carries only the key for exactly that reason; a PWA cannot
             *     call into the registry itself, so the key is resolved at read time on
             *     this side of the wire instead.
             */
            cues: string[];
            /** @example squat */
            exercise: string;
            /** @description A competition lift or a close variant, as opposed to accessory work. */
            is_primary: boolean;
            /** @example Squat */
            label: string;
            lifts: components["schemas"]["LiftView"][];
        };
        /**
         * @description The four answers to the one question asked when a session ends early (D-08).
         * @enum {string}
         */
        CutReason: "out_of_time" | "pain" | "equipment" | "enough";
        /**
         * @description Why a set was lifted at something other than the prescribed weight (D-07).
         *
         *     Optional in every direction. The chips that produce it are unselected by
         *     default, no tap is a valid answer, and nothing blocks — a default would
         *     answer the question on the athlete's behalf and land a claim nobody made in
         *     the one signal this product exists to read.
         * @enum {string}
         */
        DriftReason: "too_easy" | "too_heavy" | "already_loaded" | "felt_off";
        /** @description One athlete's run of one program. */
        Enrollment: {
            /**
             * Format: date-time
             * @description When the block ended, and `null` for exactly as long as `status` is
             *     `active` — the schema will not have it any other way.
             */
            ended_at?: string | null;
            /** Format: uuid */
            id: string;
            /** @example wendler-531-bbb */
            program_key: string;
            /** @example 5/3/1 Boring But Big */
            program_name: string;
            progress: components["schemas"]["ProgressView"];
            /**
             * @description The numbers this enrolment is prescribing from, **read-only** (D-04).
             *
             *     Served here rather than on `next-session` because of who asks. The
             *     question is "what is my program working from", which the maxes screen asks
             *     about *every* active program at once — on `next-session` that would be one
             *     request per enrolment, and each of them would also compute a prescription
             *     and a pace projection that nobody asked for. It would also go missing at
             *     the moment it is most interesting: `next-session` answers 409 once a block
             *     is finished, and where a training max ended up is exactly what an athlete
             *     looks at when a program ends.
             *
             *     It costs nothing to put here. `progress` already runs the program over the
             *     state this row carries; this runs it once more over the same bytes, with
             *     no extra query.
             */
            readout: components["schemas"]["ReadoutView"][];
            /** Format: date-time */
            started_at: string;
            status: components["schemas"]["EnrollmentStatus"];
        };
        /**
         * @description Every enrolment the athlete has ever held.
         *
         *     An object rather than a bare array, so a cursor or a count can be added
         *     without changing the type of the response (D-12).
         *
         *     Deliberately unpaginated, unlike the workout history. An enrolment is created
         *     by a deliberate human act — you press a button to start a program — so the
         *     list is bounded by how many programs someone chooses to run, which is a
         *     number in the tens over a lifetime. Workouts grow with every session and are
         *     paginated for that reason.
         */
        EnrollmentList: {
            enrollments: components["schemas"]["Enrollment"][];
        };
        EnrollmentRequest: {
            /**
             * @description A key from `GET /v1/programs`.
             * @example wendler-531-bbb
             */
            program_key: string;
        };
        /** @enum {string} */
        EnrollmentStatus: "active" | "finished" | "abandoned";
        /**
         * @description Every exercise the compiled-in programs know about.
         *
         *     An object rather than a bare array, so this can grow a cursor or a filter
         *     without changing the type of the response (D-12).
         */
        ExerciseCatalogue: {
            exercises: components["schemas"]["ExerciseSummary"][];
        };
        /** @description One exercise's share of the session. */
        ExerciseSpend: {
            /**
             * Format: int32
             * @description How many of this exercise's sets contributed an interval. Less than the
             *     number of sets performed when stamps were missing or discarded, which is
             *     what stops `seconds` being read as authoritative when it is not.
             */
            counted_sets: number;
            /** @example back-squat */
            exercise: string;
            /** @example Back Squat */
            label: string;
            /**
             * Format: int64
             * @description Summed intervals for every set of this exercise that had a believable
             *     one. Excludes the lead-in even for the first exercise.
             */
            seconds: number;
        };
        /** @description One exercise, as a client renders it in a list. */
        ExerciseSummary: {
            /**
             * @description A competition lift or a close variant, as opposed to accessory work.
             *
             *     Carried so a picker can put the lifts an athlete is likely to track a max
             *     for at the top, without a client holding its own opinion about which
             *     those are.
             */
            is_primary: boolean;
            /**
             * @description Stable key. This is what the maxes document is keyed by.
             * @example squat
             */
            key: string;
            /** @example Squat */
            label: string;
        };
        Health: {
            /** @example athletos-api */
            service: string;
            /** @example ok */
            status: string;
        };
        /**
         * @description One card. Every figure on the screen is one of these, so the client has one
         *     component and a new metric touches no client code.
         */
        Indicator: {
            /** @example load_moved */
            key: string;
            /** @example Load moved */
            label: string;
            unit: components["schemas"]["Unit"];
            /** Format: double */
            value: number;
        };
        /** @description The shape of one session's intervals: fastest, typical, slowest. */
        IntervalSpread: {
            /**
             * Format: int32
             * @description Intervals thrown away as impossible, so a screen showing these figures
             *     can say why they account for less than the wall clock.
             */
            discarded: number;
            /** Format: int64 */
            max_seconds: number;
            /**
             * Format: int64
             * @description Median, not mean. One interval spent talking to somebody moves a mean
             *     of twelve by a minute, and the tail of this distribution is not signal —
             *     the same rule, and the same reason, as [`crate::pace`].
             */
            median_seconds: number;
            /** Format: int64 */
            min_seconds: number;
        };
        /** @description An Ed25519 public key as an OKP JWK (RFC 8037). */
        Jwk: {
            /**
             * @description Algorithm the key is used with; always `EdDSA`.
             * @example EdDSA
             */
            alg: string;
            /**
             * @description Curve; always `Ed25519`.
             * @example Ed25519
             */
            crv: string;
            /** @description Key id, matching the `kid` header of tokens signed with it. */
            kid: string;
            /**
             * @description Key type; always `OKP` for Ed25519.
             * @example OKP
             */
            kty: string;
            /**
             * @description Public key use; always `sig`.
             * @example sig
             */
            use: string;
            /** @description The 32-byte public key, base64url-encoded without padding. */
            x: string;
        };
        /** @description A JSON Web Key Set (RFC 7517). */
        Jwks: {
            keys: components["schemas"]["Jwk"][];
        };
        LiftTrend: {
            bests: components["schemas"]["Best"][];
            /** @example squat */
            exercise: string;
            /** @example Squat */
            label: string;
            points: components["schemas"]["TrendPoint"][];
        };
        /** @description A number of sets at one weight and rep count. */
        LiftView: {
            /** @description When true, `reps` is a floor rather than a target — 5/3/1's "5+". */
            amrap: boolean;
            /**
             * @description Plates for **one** side of the bar, largest first, empty for anything
             *     that is not a barbell.
             *
             *     Computed server-side and sent, never derived by the client (D-11). The
             *     athlete is standing at the rack holding a phone, and "112.5 kg" is a
             *     worse answer than "bar + 25, 20, 1.25 per side".
             * @example [
             *       25,
             *       10,
             *       2.5,
             *       1.25
             *     ]
             */
            plates_per_side: number[];
            /** Format: int32 */
            reps: number;
            /** Format: int32 */
            sets: number;
            /**
             * Format: double
             * @description Kilograms, already rounded **down** to something that can actually be
             *     loaded (D-04).
             * @example 97.5
             */
            weight: number;
        };
        /** @description One set as it was recorded. */
        LoggedSetView: {
            /** Format: int32 */
            actual_reps?: number | null;
            /** Format: double */
            actual_weight?: number | null;
            drift_reason?: null | components["schemas"]["DriftReason"];
            /** @example squat */
            exercise: string;
            /**
             * @description Resolved from the compiled registry, for the same reason the session
             *     payload carries it: a browser cannot look a key up in a Rust `static`.
             *     Cues are not repeated here — a history row is read, not performed.
             * @example Squat
             */
            label: string;
            /**
             * Format: date-time
             * @description When this set was logged or skipped, as the phone recorded it (D-10).
             *     Null for anything logged before timing existed.
             */
            logged_at?: string | null;
            /**
             * @description What the athlete wrote about this set. Null for every set logged
             *     before notes existed, and for every set they had nothing to say about.
             */
            note?: string | null;
            /** Format: int32 */
            position: number;
            /** Format: int32 */
            prescribed_reps: number;
            /** Format: double */
            prescribed_weight: number;
            status: components["schemas"]["SetStatus"];
        };
        LoginRequest: {
            /** @example athlete@example.com */
            email: string;
            password: string;
        };
        LogoutRequest: {
            /**
             * @description The refresh token to kill, ending the session on this device. Optional
             *     so a client that only holds an access token can still revoke it.
             */
            refresh_token?: string | null;
        };
        /** @description The longest single gap in the session. */
        LongestInterval: {
            /** @example Back Squat */
            label: string;
            /**
             * Format: int32
             * @description The set the interval ended at — the one that was logged late, not the
             *     one before it.
             */
            position: number;
            /** Format: int64 */
            seconds: number;
        };
        /**
         * @description One athlete's maxes, keyed by exercise.
         *
         *     The same shape in both directions, so the client's form state and the
         *     response are one type. Weights are bare numbers with kilogram semantics: no
         *     unit is written into any domain type, which is what makes offering pounds
         *     later a UI change and not a migration (D-04).
         */
        MaxesDocument: {
            /**
             * @example {
             *       "bench": 100,
             *       "deadlift": 180,
             *       "military-press": 60,
             *       "squat": 140
             *     }
             */
            maxes: {
                [key: string]: number;
            };
        };
        /** @description The session the enrolment is currently pointing at. */
        NextSession: {
            /** @description The prescription as the athlete reads it: one entry per exercise. */
            blocks: components["schemas"]["BlockView"][];
            /** Format: int32 */
            day: number;
            /** Format: uuid */
            enrollment_id: string;
            /**
             * @description The exercise key this session is built around, when there is one. A key
             *     rather than a title, so it is data a client can act on.
             */
            focus?: string | null;
            /**
             * @description When this session will be over, at the athlete's own pace (D-10).
             *
             *     Added in phase 5, and served here rather than on an endpoint of its own
             *     because this is the only screen that asks the question. The peek page
             *     shows the projection and the logger caches it with the committed session,
             *     so a separate endpoint would be a second request that every caller of the
             *     first one makes — and the header would then be drawable only after both
             *     landed. It also keeps the *offline* story intact: what the phone caches at
             *     commit is one response, and the pace is in it.
             *
             *     The cost is one more query on a read-only handler, over the same
             *     enrolments the athlete already owns. Peeking still writes nothing (D-08).
             */
            pace: components["schemas"]["PaceProjection"];
            /**
             * @description The same prescription as the athlete *logs* it: every set, expanded and
             *     numbered.
             *
             *     Committing to a session materialises every prescribed set locally with
             *     `status: pending` (D-08), and this is that list, already built. It is
             *     here rather than left to the client because `position` is a persisted
             *     key — `workout_sets` is unique on `(workout_id, position)` — and a number
             *     that the server enforces should be a number the server issued. It also
             *     keeps the round trip symmetric: what comes back in `POST /v1/workouts` is
             *     this list with the `actual_*` fields and a status filled in.
             */
            prescribed_sets: components["schemas"]["PrescribedSet"][];
            program_key: string;
            progress: components["schemas"]["ProgressView"];
            /** Format: int32 */
            week: number;
        };
        /**
         * @description What the session header needs, with the arithmetic already done.
         *
         *     Every field is a fact about *this* athlete and *this* session. There is
         *     deliberately nothing here that would let a client recompute the median for
         *     itself, because a client that could would eventually be asked to.
         */
        PaceProjection: {
            /**
             * @description Whether the athlete has logged enough to project from (D-10).
             *
             *     Not the same question as `projected_seconds != null`, though today they
             *     answer together: this one is about the athlete's history, and a session
             *     with nothing prescribed in it would have a pace to project *from* and
             *     nothing to project *onto*. A client branching on "do I show the finish
             *     time" wants this one, and a name reads better at the call site than a
             *     null check whose meaning has to be looked up.
             */
            can_project: boolean;
            /**
             * Format: double
             * @description The athlete's median seconds per set, or `null` when there is not enough
             *     history to say.
             *
             *     Carried so the logger can re-project as sets are logged, with no network
             *     (D-09). It is a measurement the server made, not an input the client is
             *     expected to reason about.
             * @example 96
             */
            median_seconds_per_set?: number | null;
            /**
             * Format: int64
             * @description How long this whole session should take at that pace, in seconds.
             *
             *     Whole seconds, and every prescribed set counted — this is the number the
             *     peek screen shows before a single set exists to be remaining. `null`
             *     whenever there is no pace, because an invented finish time is worse than
             *     none, for the same reason an invented progress denominator is (D-03).
             * @example 3264
             */
            projected_seconds?: number | null;
            /**
             * Format: int32
             * @description How many of the recent sessions were usable — the number the floor is
             *     compared against, not the number of sessions looked at.
             *
             *     Sent because "not yet" is a more useful answer with a count attached: a
             *     client can say "one more session" rather than going quiet for reasons the
             *     athlete cannot see.
             * @example 5
             */
            sample_size: number;
        };
        /**
         * @description What comes off the bar and what goes on, to get to this set's weight
         *     (D-04).
         *
         *     Mirrored from [`athletos_training::PlateChange`] because the training crate
         *     depends on `serde`, `serde_json` and `thiserror` and nothing else (D-15),
         *     so it cannot carry a `ToSchema` of its own.
         */
        PlateChangeView: {
            /**
             * @description Per side, largest first — the order they go on.
             * @example [
             *       15
             *     ]
             */
            add: number[];
            /**
             * @description What this leaves on the bar, largest first. Sums to
             *     `prescribed_weight`, and is deliberately not always the greedy
             *     breakdown that `plates_per_side` carries.
             * @example [
             *       25,
             *       15
             *     ]
             */
            plates_per_side: number[];
            /**
             * @description Per side, outermost first — the order they actually come off.
             * @example [
             *       1.25,
             *       2.5
             *     ]
             */
            remove: number[];
        };
        /** @description One prescribed set, ready to be logged. */
        PrescribedSet: {
            amrap: boolean;
            exercise: string;
            /**
             * @description The exercise's display name, resolved from the compiled registry.
             * @example Squat
             */
            label: string;
            plate_change?: null | components["schemas"]["PlateChangeView"];
            /**
             * @description The same breakdown [`LiftView::plates_per_side`] carries, repeated here.
             *
             *     Added in phase 4. The logger walks `prescribed_sets`, not `blocks`, and
             *     the athlete needs the plates on the screen they are actually looking at.
             *     Without this the client has to join the two lists — by position, which
             *     means reimplementing this module's expansion order, or by
             *     `(exercise, weight)`, which is a lookup the server can simply answer. A
             *     few duplicated floats are cheaper than either (D-11).
             * @example [
             *       25,
             *       10,
             *       2.5,
             *       1.25
             *     ]
             */
            plates_per_side: number[];
            /**
             * Format: int32
             * @description Order within the session, from zero. Persisted, and unique per workout.
             */
            position: number;
            /** Format: int32 */
            prescribed_reps: number;
            /** Format: double */
            prescribed_weight: number;
        };
        /**
         * @description RFC 9457 problem details. `type` is omitted until we publish stable problem
         *     type URIs; consumers should branch on `status` plus `title` for now.
         */
        ProblemDetails: {
            /** @description Human-readable explanation specific to this occurrence. */
            detail: string;
            /**
             * Format: int32
             * @description HTTP status code, repeated in the body per RFC 9457.
             * @example 404
             */
            status: number;
            /**
             * @description Short, human-readable summary of the problem type.
             * @example Not Found
             */
            title: string;
        };
        /**
         * @description The catalogue, in registry order.
         *
         *     An object rather than a bare array so that the day this needs a cursor, a
         *     count or a per-athlete fit marker, it can have one without changing the type
         *     of the response (D-12).
         */
        ProgramCatalogue: {
            programs: components["schemas"]["ProgramSummary"][];
        };
        /** @enum {string} */
        ProgramEquipment: "barbell" | "squat_rack" | "bench" | "dumbbells" | "pull_up_bar";
        /** @enum {string} */
        ProgramExperience: "novice" | "intermediate" | "advanced";
        /**
         * @description Whether the program ends.
         *
         *     The same distinction the session payload's `progress.total` makes at runtime:
         *     a fixed block has an honest denominator, an open-ended one has none and must
         *     not be given an invented one (D-03).
         */
        ProgramLength: {
            /** @enum {string} */
            kind: "fixed";
            /** Format: int32 */
            sessions: number;
            /** Format: int32 */
            weeks: number;
        } | {
            /** @enum {string} */
            kind: "open_ended";
        };
        /**
         * @description How much the program costs to recover from — the axis D-01 cares about most.
         *     Three coarse steps on purpose: it is a warning, not a measurement.
         * @enum {string}
         */
        ProgramRecoveryDemand: "moderate" | "high" | "brutal";
        /**
         * @description Everything an athlete needs in order to judge whether a program fits.
         *
         *     There is no fit score and no ranking (D-01). `recovery_demand` and
         *     `estimated_session_minutes` lead because they are the two axes that matter
         *     to someone who over-reaches and who has an hour — a 75-minute program should
         *     announce itself before enrolment, not in week three.
         */
        ProgramSummary: {
            /** Format: int32 */
            days_per_week: number;
            equipment: components["schemas"]["ProgramEquipment"][];
            /**
             * Format: int32
             * @description Wall-clock minutes for a typical session, including rest.
             * @example 55
             */
            estimated_session_minutes: number;
            experience_floor: components["schemas"]["ProgramExperience"];
            /**
             * @description Stable key. This is what `POST /v1/enrollments` takes.
             * @example wendler-531-bbb
             */
            key: string;
            length: components["schemas"]["ProgramLength"];
            /** @example 5/3/1 Boring But Big */
            name: string;
            recovery_demand: components["schemas"]["ProgramRecoveryDemand"];
            /**
             * @description The one-rep maxes this program refuses to start without (D-04).
             *
             *     Here so that a client can render the maxes form *before* enrolling,
             *     without holding its own copy of which lifts which program wants. The
             *     alternative was the 422 from `POST /v1/enrollments`, which names one
             *     missing key at a time and only after the athlete has pressed the button.
             *
             *     Labels are resolved from the compiled exercise registry for the same
             *     reason `BlockView` resolves them: a browser cannot look a key up in a
             *     Rust `static`, and a `/v1/exercises` endpoint to cache would be a round
             *     trip before the first form renders.
             */
            required_maxes: components["schemas"]["RequiredMax"][];
        };
        ProgramTotals: {
            /** Format: uuid */
            enrollment_id: string;
            indicators: components["schemas"]["Indicator"][];
            /** @example wendler-531-bbb */
            program_key: string;
            /** @example 5/3/1 Boring But Big */
            program_name: string;
            /** @example active */
            status: string;
        };
        /** @description Sessions completed, and the denominator if there is an honest one. */
        ProgressView: {
            /** Format: int32 */
            completed: number;
            /**
             * Format: int32
             * @description `null` for an open-ended program. A client showing a percentage needs
             *     this; one that invented a denominator would be lying (D-03).
             */
            total?: number | null;
        };
        /**
         * @description One number a program is currently working from, and what kind of number it
         *     is.
         *
         *     The mirror of the engine's `Readout`, with the exercise's display name added
         *     the way `BlockView` adds it — a browser cannot look a key up in a Rust
         *     `static`, and this list is short enough that a second round trip to label it
         *     would be absurd.
         *
         *     There is no PUT for any of this and there must not be. A training max is the
         *     governor a program applies to an athlete who over-reaches (D-01), and letting
         *     them nudge it after a session that felt easy is letting them undo the
         *     restraint (D-04). Visible and read-only is the whole shape of the decision:
         *     the athlete may watch the number, and may not touch it.
         */
        ReadoutView: {
            /**
             * @description The exercise this number applies to, as a registry key.
             * @example squat
             */
            exercise: string;
            /**
             * @description The exercise's display name, resolved from the compiled registry.
             * @example Squat
             */
            exercise_label: string;
            /**
             * @description What the number *is*, in the program's own words.
             *
             *     This is the field that stops the screen lying. "126" next to an entered
             *     max of 140 is inexplicable; "Training max 126" against "Entered 1RM 140"
             *     is the program doing its job. Only the program knows which it is — 5/3/1
             *     took 90% and has been moving it ever since, a fixed block took the number
             *     straight and froze it — so the words come from there and not from here.
             * @example Training max
             */
            label: string;
            /**
             * Format: double
             * @description Kilograms, unrounded. Unlike a prescribed weight this is not something to
             *     load on a bar; it is the number the loadable weights are derived from
             *     (D-04).
             * @example 126
             */
            weight: number;
        };
        /**
         * @description How a session that is already recorded turned out.
         *
         *     A second enum rather than a `Serialize` on [`WorkoutOutcome`], because the
         *     two vocabularies are genuinely different sizes: a client may only ever
         *     *claim* `completed` or `cut_short`, but it must be able to *read* the
         *     `auto_closed` the stale-session sweep writes (D-08). Collapsing them into one
         *     type would mean either letting a client claim `auto_closed` or hiding it from
         *     the history, and both are worse than two enums that happen to overlap.
         * @enum {string}
         */
        RecordedOutcome: "completed" | "cut_short" | "auto_closed";
        RefreshRequest: {
            /** @description The opaque refresh token most recently issued to this client. */
            refresh_token: string;
        };
        RegisterRequest: {
            /**
             * @description The athlete's own name, shown back to them and used as context the
             *     password may not be built out of.
             * @example Alex Berg
             */
            display_name: string;
            /** @example athlete@example.com */
            email: string;
            /**
             * @description Checked against the guessability policy of NIST SP 800-63B-4 §3.1.1.2
             *     before the account exists — see `auth::password`.
             */
            password: string;
        };
        /** @description One lift a program needs a max for, ready to be a labelled form field. */
        RequiredMax: {
            /** @example military-press */
            exercise: string;
            /** @example Military Press */
            label: string;
        };
        /** @description One session, for the load panel and the drift band. */
        SessionFigures: {
            /** Format: date-time */
            at: string;
            /** Format: int64 */
            duration_seconds?: number | null;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: double */
            load_moved_kg: number;
            /**
             * Format: double
             * @description Summed over **every** set the session prescribed, whatever its status —
             *     unlike [`crate::report::SessionReport::load_prescribed_kg`], which sums
             *     only the done sets on the finish-screen receipt. That field answers
             *     "how far did the weight I actually lifted drift from what was asked?",
             *     uncontaminated by work not done. This one answers a different question:
             *     "how much did the program ask for, whether or not I did it?" — so a
             *     session with half its sets skipped reads as a shortfall here rather
             *     than as perfect compliance. Both are correct for their own panel, which
             *     is exactly why they carry different names on `/v1` rather than one
             *     field meaning two things depending which endpoint sent it.
             */
            load_planned_kg: number;
            /** Format: int32 */
            sets_over: number;
            /** Format: int32 */
            sets_under: number;
            /** Format: uuid */
            workout_id: string;
        };
        /** @description What the finish screen says, computed here so no client has to (D-11). */
        SessionReport: {
            /**
             * Format: int64
             * @description The athlete's average across this **enrolment's** other recorded
             *     sessions — same block, same training max, so it compares like with
             *     like. `None` below three of them, the same rule and the same reason as
             *     [`crate::pace`]: not shown before there is data to compute it from.
             */
            average_duration_seconds?: number | null;
            /** Format: int64 */
            duration_seconds: number;
            intervals?: null | components["schemas"]["IntervalSpread"];
            /**
             * Format: double
             * @description Summed over **done sets only**, as performed.
             */
            load_moved_kg: number;
            /**
             * Format: double
             * @description Summed over the same done sets, as asked for. The gap between the two
             *     is weight drift, uncontaminated by work not done.
             */
            load_prescribed_kg: number;
            /**
             * Format: int32
             * @description Done sets lifted heavier than prescribed. The count is the part that
             *     can be acted on: a kilogram total alone does not distinguish one wild
             *     set from twelve small ones.
             */
            sets_over: number;
            /** Format: int32 */
            sets_under: number;
        };
        /** @description Where one session's time went. */
        SessionTiming: {
            /**
             * Format: int32
             * @description Intervals thrown away as impossible — negative, or over the ceiling.
             *
             *     Reported rather than hidden. When this is not zero the totals below add
             *     up to less than the wall clock, and the screen has to be able to say why
             *     instead of leaving the athlete to notice the arithmetic does not work.
             */
            discarded_intervals: number;
            /**
             * @description Per exercise, in the order the exercises were first performed.
             *
             *     Order matters and is not alphabetical: an athlete reading this is
             *     walking back through their own session, and the main lift they opened
             *     with belongs at the top.
             */
            exercises: components["schemas"]["ExerciseSpend"][];
            /**
             * Format: int64
             * @description Commit to the first set logged: walking in, changing, warming up.
             *
             *     `None` when no set carries a stamp, which is also when the whole
             *     structure is absent — see [`compute`].
             */
            lead_in_seconds?: number | null;
            longest_interval?: null | components["schemas"]["LongestInterval"];
            /**
             * Format: int64
             * @description The last set logged to the end of the session. `None` while the session
             *     is still open, since there is nothing to measure to.
             */
            tail_seconds?: number | null;
            /**
             * Format: int32
             * @description How many sets carried no stamp at all.
             *
             *     Not the same as `discarded_intervals`: this is work that was never
             *     measured, that one is a measurement that could not be believed.
             */
            unstamped_sets: number;
        };
        /** @enum {string} */
        SetStatus: "done" | "skipped" | "pending";
        /**
         * @description One set: what was asked for and what happened (D-07).
         *
         *     Four numbers, not two. Going heavier than prescribed means editing the
         *     number, and it is logged as edited — a cap would produce either dishonest
         *     logs or an abandoned app, and honesty must never cost more than dishonesty.
         */
        SubmittedSet: {
            /** Format: int32 */
            actual_reps?: number | null;
            /**
             * Format: double
             * @description Required when `status` is `done`; the schema will not record a set as
             *     done with no numbers, because that is a hole in every drift query that
             *     will ever run over this table.
             */
            actual_weight?: number | null;
            drift_reason?: null | components["schemas"]["DriftReason"];
            exercise: string;
            /**
             * Format: date-time
             * @description When the athlete tapped Log or Skip for this set, from the phone's clock
             *     at that moment (D-10).
             *
             *     Optional, and additively so (D-12): a client that does not send it still
             *     submits a valid workout, it simply has no timing to show afterwards.
             *     Stamped on the device rather than here because the logger runs offline
             *     and a submission can arrive hours late — a server clock would be
             *     measuring when the queue flushed, not when the work happened.
             *
             *     Not validated against `started_at` and `ended_at`. A stamp outside them
             *     is a phone whose clock moved, which is a fact about the measurement
             *     rather than a malformed request, and refusing the submission would cost
             *     the athlete a whole session's log over it. `timing` discards the
             *     intervals it cannot believe instead.
             */
            logged_at?: string | null;
            /**
             * @description What the athlete wrote about this set, if anything (D-07).
             *
             *     Optional and additively so (D-12). Blank and whitespace-only strings
             *     normalise to `None` rather than being refused — a note that was typed
             *     and then cleared is not an error, and the athlete is holding a phone
             *     with chalk on their hands.
             *
             *     Over 500 characters is a 422 naming the position. Truncating would
             *     store something other than what was written, which is worse than
             *     refusing it.
             */
            note?: string | null;
            /**
             * Format: int32
             * @description From `prescribed_sets[].position` in the session payload. Unique within
             *     the submission.
             */
            position: number;
            /** Format: int32 */
            prescribed_reps: number;
            /** Format: double */
            prescribed_weight: number;
            status: components["schemas"]["SetStatus"];
        };
        /**
         * @description A new pair of credentials. The refresh token is single-use: the next call to
         *     `/v1/auth/refresh` invalidates it and returns its successor.
         */
        TokenPair: {
            /** @description Ed25519-signed JWT. Verifiable against `/.well-known/jwks.json`. */
            access_token: string;
            /**
             * Format: int64
             * @description Access token lifetime in seconds.
             * @example 900
             */
            expires_in: number;
            /** @description Opaque refresh token — not a JWT, and revocable. */
            refresh_token: string;
            /**
             * Format: date-time
             * @description When the refresh token stops working, RFC 3339.
             */
            refresh_token_expires_at: string;
            /** @example Bearer */
            token_type: string;
        };
        /** @description One session's contribution to a lift's trend. */
        TrendPoint: {
            /** Format: date-time */
            at: string;
            /**
             * Format: double
             * @description Signed: positive is heavier than prescribed, negative lighter. Summed
             *     over that session's done sets of this lift, against the same sets'
             *     prescriptions, so it is weight drift uncontaminated by work not done.
             */
            drift_kg: number;
            /**
             * Format: double
             * @description The best estimate across that session's done sets of this lift. `None`
             *     when every set was skipped, or every set was above the rep ceiling.
             */
            estimate?: number | null;
            /**
             * @description Every reason the athlete gave on this lift that session. Travels on
             *     every point; the screen renders them only on downward moves, and that
             *     test is presentation rather than a fact about training.
             */
            reasons: string[];
            /** Format: int32 */
            sets_over: number;
            /** Format: int32 */
            sets_under: number;
            /**
             * Format: double
             * @description What the program was prescribing from during that session. `None` for
             *     every session logged before `enrollment_advances` existed — the chart
             *     must draw a gap rather than a zero.
             */
            training_max?: number | null;
            /** Format: uuid */
            workout_id: string;
        };
        /**
         * @description What a figure is measured in. A tag, not a display string — the client
         *     decides whether 3600 seconds reads as "1:00" or "60 min" (D-04).
         * @enum {string}
         */
        Unit: "kg" | "count" | "seconds";
        /**
         * @description One workout, expanded.
         *
         *     The summary is nested rather than flattened so that the two responses cannot
         *     drift: a field added to the history row is a field this endpoint gains for
         *     free, and there is exactly one place that builds it.
         */
        WorkoutDetail: {
            notes?: string | null;
            /**
             * @description Every set as it was logged, in position order — including the ones never
             *     done. Both the prescribed and the actual numbers, because drift is the
             *     thing this screen exists to show (D-07, D-13).
             */
            sets: components["schemas"]["LoggedSetView"][];
            timing?: null | components["schemas"]["SessionTiming"];
            workout: components["schemas"]["WorkoutSummary"];
        };
        /** @description A page of history, newest first. */
        WorkoutHistory: {
            /**
             * Format: int32
             * @description The limit actually applied, which is not always the one asked for.
             */
            limit: number;
            /** Format: int32 */
            offset: number;
            /**
             * Format: int64
             * @description Every workout matching the filter, not just this page — what a "load
             *     more" control needs in order to know when to stop.
             */
            total: number;
            workouts: components["schemas"]["WorkoutSummary"][];
        };
        /**
         * @description How the session ended, as the athlete may report it.
         *
         *     Deliberately missing the schema's third value, `auto_closed`. That one
         *     belongs to the sweep that closes a session left open past three hours (D-08),
         *     and a client must not be able to claim it.
         * @enum {string}
         */
        WorkoutOutcome: "completed" | "cut_short";
        /** @description What the server recorded, and where the program stands afterwards. */
        WorkoutReceipt: {
            /** Format: int32 */
            day: number;
            /**
             * @description True when this submit was a retry of one already accepted, and therefore
             *     changed nothing. The status code says the same thing: 201 the first time,
             *     200 for every retry.
             */
            duplicate: boolean;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: uuid */
            id: string;
            /**
             * @description Progress *after* the submit. A retry reports the same numbers the first
             *     attempt did, which is the whole point.
             */
            progress: components["schemas"]["ProgressView"];
            /**
             * @description What this session cost, and how it compares (D-08, amended).
             *
             *     Present on a retry too, and computed the same way — see `recorded_report`.
             */
            summary: components["schemas"]["SessionReport"];
            /**
             * Format: int32
             * @description Where in the program this session sat — decided by the server from the
             *     enrolment's state, not taken from the request (D-11).
             */
            week: number;
        };
        /** @description A finished session, as the phone recorded it. */
        WorkoutSubmission: {
            cut_reason?: null | components["schemas"]["CutReason"];
            /** Format: date-time */
            ended_at: string;
            /**
             * Format: uuid
             * @description Must belong to the authenticated athlete. Someone else's is a 404.
             */
            enrollment_id: string;
            /**
             * Format: uuid
             * @description **Minted by the client**, before the session started and before it had a
             *     network, and the idempotency key for this whole endpoint (D-09).
             *
             *     A UUIDv7 by convention, because time-ordered ids cluster in the primary
             *     key's btree. It is not *checked* to be v7: the idempotency comes from the
             *     primary key and works for any uuid, whereas refusing a v4 would strand a
             *     queued offline workout in a retry loop it could never get out of, with no
             *     action the athlete could take to fix it.
             */
            id: string;
            notes?: string | null;
            outcome: components["schemas"]["WorkoutOutcome"];
            /**
             * @description Every set of the session, including the ones that were never done.
             *
             *     `pending` and `skipped` are first-class outcomes rather than absent rows:
             *     what was prescribed and not performed is precisely how "work not done"
             *     becomes the second axis of drift (D-07, D-08).
             */
            sets: components["schemas"]["SubmittedSet"][];
            /**
             * Format: date-time
             * @description Wall clock from the phone, stamped when the athlete committed to the
             *     session — never when they merely looked at it (D-08).
             */
            started_at: string;
        };
        /**
         * @description One row of the history list.
         *
         *     Exactly what a history row shows and nothing else: when, which program,
         *     where in it, how long it took, and how it ended. `notes` and the set list are
         *     on the detail endpoint, because they are what the row expands *into*.
         */
        WorkoutSummary: {
            cut_reason?: null | components["schemas"]["CutReason"];
            /** Format: int32 */
            day: number;
            /**
             * Format: int64
             * @description Wall clock, in seconds — the only measure of "the hour" there is (D-10).
             *
             *     Subtracted here rather than left to the client. Two clients doing date
             *     arithmetic on two timestamps is two implementations of one rule, and the
             *     second one is written in a different language (D-11). `null` while a
             *     session is still open, which today means never: `POST /v1/workouts`
             *     requires both ends.
             * @example 3600
             */
            duration_seconds?: number | null;
            /** Format: date-time */
            ended_at?: string | null;
            /** Format: uuid */
            enrollment_id: string;
            /** Format: uuid */
            id: string;
            outcome?: null | components["schemas"]["RecordedOutcome"];
            /** @example wendler-531-bbb */
            program_key: string;
            /** @example 5/3/1 Boring But Big */
            program_name: string;
            /** Format: date-time */
            started_at: string;
            /** Format: int32 */
            week: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    jwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The active JSON Web Key Set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jwks"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dependencies are reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description A dependency is unreachable */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    show_maxes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The athlete's maxes, possibly none */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaxesDocument"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    replace_maxes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaxesDocument"];
            };
        };
        responses: {
            /** @description The maxes as now stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaxesDocument"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description An unknown exercise key or an implausible weight */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Credentials accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Unknown address or wrong password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many consecutive failures for this address; `Retry-After` says how long to wait (ADR-0017) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description The session is ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Neither a refresh token nor an access token was presented */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated athlete */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedAthlete"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A new token pair */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description The refresh token is unknown, spent, expired or revoked */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account exists and is signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description An account already uses that address */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The address, name or password was refused */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_enrollments: {
        parameters: {
            query?: {
                /**
                 * @description One of `active`, `finished` or `abandoned`. Omitted returns all of them.
                 *
                 *     A `String` parsed by hand rather than the `EnrollmentStatus` enum
                 *     deserialized straight from the query string. Two reasons: the refusal can
                 *     then name the legal values, where a deserializer rejection is a bare 400
                 *     with none of the RFC 9457 shape the rest of this API answers in; and a
                 *     query parameter typed as a closed vocabulary is a parameter that cannot
                 *     grow, which is the one thing `/v1` may never do (D-12).
                 * @example active
                 */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The athlete's enrolments, active first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentList"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description `status` is not one of the three */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    create_enrollment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentRequest"];
            };
        };
        responses: {
            /** @description Enrolled */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No program has that key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The athlete has not entered a max this program needs */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    next_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The enrolment's id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The next session, with plate breakdowns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NextSession"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such enrolment belongs to this athlete */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The enrolment is over, or the block has no session left */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_exercises: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The exercise registry, in registry order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseCatalogue"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_programs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The catalogue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramCatalogue"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    show_program: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description The program's registry key
                 * @example smolov-jr
                 */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The program */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSummary"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No program has that key */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    athlete_progress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A year of training, derived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AthleteProgress"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    list_workouts: {
        parameters: {
            query?: {
                /**
                 * @description Only this enrolment's workouts — "how did that block go".
                 *
                 *     Worth having beyond convenience: with it supplied the query is one walk
                 *     of `workouts_enrollment_id_idx (enrollment_id, started_at desc)` and
                 *     needs no sort at all, which the athlete-wide query cannot manage.
                 */
                enrollment_id?: string;
                /**
                 * @description Rows per page. Defaults to 25, clamped to 100.
                 * @example 25
                 */
                limit?: number;
                /**
                 * @description Rows to skip. Defaults to 0.
                 * @example 0
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of history, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutHistory"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    submit_workout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkoutSubmission"];
            };
        };
        responses: {
            /** @description A retry of a submit already accepted; nothing moved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutReceipt"];
                };
            };
            /** @description Recorded, and the program advanced */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutReceipt"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such enrolment belongs to this athlete */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The enrolment has nothing left to log, or the id is already used by another enrolment */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Too many sets in one submission */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description The submission is inconsistent */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    show_workout: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The workout's id — the one the client minted */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The workout, with every set as logged */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkoutDetail"];
                };
            };
            /** @description Missing or invalid access token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description No such workout belongs to this athlete */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
